FILES		= megaphone.cpp

NAME		= megaphone

RM			= rm -f

CC			= c++

CFLAGS		= -Wall -Wextra -Werror -std=c++98 -g

OBJ		= $(FILES:.cpp=.o)

all:		${NAME}

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re